products for dr6v4
simonsobs/sofind pull request #4
Opened 2023-12-24 11:34 UTC by iabrilcabezas

- added data model dr6v4_day
- added products: calibrations (from calibrations branch by Zach), transfer function, beams. 
- expanded masks product to read lensing masks; **`/masks/__init__.py` has changed, please review for backwards compatibility**
- added documentation
- example of usage of new features can be found here https://github.com/ACTCollaboration/DR6plus_lensing/blob/main/exploration/sofind_example.ipynb

2024-01-11 20:47 UTC, zatkins2 commented on sofind/qids/act_dr6vX_qids.yaml
agreed, it's annoying how the filenames for the v4 daytime maps are slightly different than v3. i guess we will never look at the v3 daytime maps so this change is fine (as opposed to making a separate `qid_config file` for v3 and v4)

2024-01-11 21:35 UTC, zatkins2 commented on sofind/products/transfer_func/__init__.py
I made a minor change here (with corresponding changes in the yaml files) so that the yaml files didn't have like `tf_dr6v4_230523` as a block within the yaml file (it's not necessary)

2024-01-11 22:20 UTC, zatkins2 commented on sofind/products/masks/__init__.py
Ok. We can try to clean it up a little more later, but for now, I think I'd simplify the new mask features you implemented a little bit. Correct me if I'm wrong, but looking at `lensing_masks`, the mask names aren't actually dynamic. I.e., rather than having some info be keyed in the calibration file and then used to format the filename, you could have just printed the filename, and there wouldn't be a loss of functionality or generality. 

So, I'd propose instead that under each mask type in the config you just list the fully populated filename associated with that mask type, perhaps under the key `mask_fn`. See the new mask type `how_about_this_instead` that I added that would replace `wide_v4_20220316` (if you like it, please change the other masks and revert the name of this mask type to `wide_v4_20220316`).

I've also changed to code here to go ahead with that change, but lmk if it works for you (if not, we'll figure out what to do).

2024-01-11 22:31 UTC, zatkins2 commented on sofind/products/maps/act_dr6v4_day.yaml
It looks like all the daytime map info can be accommodated by the current `act_dr6v4` config file with no changes, *except* the location of the maps on `dirac` (the directories for night and day maps is different apparently). I'd prefer to not add a new maps configuration file if we don't have to -- is it not possible to store the day maps in the same directory as the night maps on `dirac`?

If they can be moved into the same directory, then we don't need this new config file. Instead, you could just add the daytime qid-related info to the `allowed_qids` and `allowed_qids_extra_kwargs`. Then, all the user would have to do to load a day map would be to supply the appropriate day `qid`, which is cleaner than also having to supply the correct `subproduct`.

2024-01-11 22:42 UTC, zatkins2 commented on sofind/qids/nemo_qids.yaml
I'm thinking that nemo beams should be a beam subproduct of act_dr6v4 beams (assuming they go with dr6v4).

Perhaps this is why you were asking how to extract just the `freq` info for a qid, but I think a better thing than having new nemo qids would be to extract the `freq` info from the supplied qid (e.g. `f150` from `pa6b`) and then use that to get the correct nemo beam?

2024-01-11 22:47 UTC, zatkins2 commented on sofind/qids/nemo_qids.yaml
Actually, yeah, I see why that's tricky -- you'd need to change the implementation in a messy way of the beam `__init__.py` to accomplish that (e.g., if it's a nemo beam, do something different). 

I think the best thing is this (even though a little clunky): add to the `beams_nemo` the `nemo_tag` additional qid kwarg for every allowed qid (presumably, not pa4b which is f220). If the qid is f090, give it the right nemo_tag, etc...

2024-01-11 22:59 UTC, zatkins2 commented on sofind/products/beams/beams_v4_20230130.yaml
I really think the `snfit` thing should just be a separate subproduct. If you agree, please remove the `beam_name` functionality from the `__init__.py` file.

2024-01-11 23:02 UTC, zatkins2 commented on sofind/products/calibrations/dr6v4_cal_230523.yaml
Hm...just checking, it's really true that there's no cal version you need that has both `cals` and `poleffs`?

2024-01-11 23:03 UTC, zatkins2 commented on sofind/products/beams/beams_v4_20230130.yaml
Also, just checking, there is a Sep 2023 beam version...are you sure you don't need it?

2024-01-11 23:08 UTC, zatkins2 commented on sofind/products/noise_models/act_dr6v4_day.yaml
Everything looks good except this part: `data_model_name: act_dr6v4_day`. Please see my other comments on the data_models re. the necessity of the `act_dr6v4_day` data_model. If you agree there, then you can change `act_dr6v4_day` to `act_dr6v4`.

Also, just checking, the exact same noise model parameters worked for the daytime maps as the nighttime maps? That's cool

2024-01-11 23:11 UTC, zatkins2 commented on sofind/datamodels/act_dr6v4_day.yaml
Hm can't all of these be folded into the existing `act_dr6v4` data_model by adding day-specific subproducts for maps and noise models?

In fact, see my below comments, but for maps at least, I think we don't need a day-specific maps config either.

2024-01-11 23:12 UTC, zatkins2 requested changes
This is a seriously impressive and useful amount of work. I'm super happy to have a partner in pushing `sofind` to new heights :)

Take a look at the comments I left and let me know if anything is confusing. In particular, there are some changes to implementation (beams, masks) that I would advocate for. Let me know if my suggestions would break lensing codes.

2024-01-17 12:06 UTC, iabrilcabezas commented on sofind/qids/act_dr6vX_qids.yaml
yes, not planned to look into the v3 daytime data

2024-01-17 19:22 UTC, iabrilcabezas commented on sofind/products/transfer_func/__init__.py
aaah cool

2024-01-17 20:06 UTC, iabrilcabezas commented on sofind/products/masks/__init__.py
Ahhh, thanks. I have now extended the change to the other masks. 

At some point, I will hardcode same mask but different sky fractions, since there are some null tests we run by changing the sky fraction. Does that sound OK to you?

2024-01-18 10:54 UTC, iabrilcabezas commented on sofind/products/maps/act_dr6v4_day.yaml
done

2024-01-18 11:07 UTC, iabrilcabezas commented on sofind/products/noise_models/act_dr6v4_day.yaml
amended.

I have not validated the noise sims so I am not sure yet about the noise model parameters, sorry.

2024-01-18 11:09 UTC, iabrilcabezas commented on sofind/datamodels/act_dr6v4_day.yaml
maybe we wait to add noise_model for day until we have validated sims

2024-01-18 19:28 UTC, zatkins2 commented on sofind/datamodels/act_dr6v4_day.yaml
Ok

2024-01-18 19:47 UTC, zatkins2 commented on sofind/products/maps/act_dr6v4_day.yaml
Nice!

2024-01-18 19:48 UTC, zatkins2 commented on sofind/products/noise_models/act_dr6v4_day.yaml
Ok

2024-01-18 20:09 UTC, zatkins2 commented on sofind/products/masks/__init__.py
I think the skyfraction thing can be accommodated without hardcoding filenames or changes to the code. I think you'd be able to use the exsiting `kwargs` argument to pass some extra info (e.g. `skyfrac=` or whatever) which will be used to format the filename. As long as a filename format string in the config has a `skyfrac` field it will populate; if not, it will do nothing.

2024-01-19 17:08 UTC, iabrilcabezas commented on sofind/qids/nemo_qids.yaml
thank you, this is now in.

2024-01-19 18:08 UTC, iabrilcabezas commented on sofind/products/masks/__init__.py
done!

2024-01-19 18:15 UTC, iabrilcabezas commented on sofind/products/beams/beams_v4_20230130.yaml
created separate subproduct + added Sept 2023 beams

2024-01-19 18:15 UTC, iabrilcabezas commented on sofind/products/calibrations/dr6v4_cal_230523.yaml
it's a mess I know

2024-01-19 18:20 UTC, iabrilcabezas commented on sofind/products/calibrations/dr6v4_cal_230523.yaml
at least now `dr6v4_cal_231113` has both :)

2024-01-27 17:30 UTC, zatkins2 commented on sofind/qids/nemo_qids.yaml
nice! looks clean :)

2024-01-27 17:33 UTC, zatkins2 commented on sofind/products/beams/beams_v4_20230130.yaml
cool looks good; tpol then is passed as a `kwarg` to the beam functions as needed (if using the `snfit` subproduct)

2024-01-27 17:41 UTC, zatkins2 commented
PR looks ready! I think best if we change target to `develop` (which is on the same commit as `main`), then we can deal with calibrations on a new branch and submit any last-minute needed commits

2024-01-31 16:11 UTC, zatkins2 approved these changes
Good to merge to `develop`!

2024-01-31 16:11 UTC, merged