daytime noise models
simonsobs/sofind pull request #8
Opened 2024-10-02 17:01 UTC by iabrilcabezas

noise models estimated using "lensing_masks"
they are only good for lensing analyses (5% error ell > 600)
daywide: pa5
daydeep: pa5, pa6

2024-10-02 17:08 UTC, iabrilcabezas commented
it also has some extra nemo beams and a new calibrations class

2024-10-07 16:33 UTC, zatkins2 commented on sofind/products/beams/__init__.py
can you add a small docstring for the new function

2024-10-07 16:38 UTC, zatkins2 commented on sofind/products/beams/beams_v4_20240115.yaml
this is a new filename scheme `beam_full_{array}_{freq}_{daynight}_beam.txt` vs current nighttime beams I think. Did adri or sigurd make this product? Is it only for daytime? If it's only for daytime, I'd suggest a different name for this yaml file because the yaml name suggests its the next version of nighttime beam,s

2024-10-07 16:39 UTC, zatkins2 commented on sofind/products/calibrationspkl/__init__.py
please add some quick docstrings :)

2024-10-07 16:43 UTC, zatkins2 requested changes
Love it. You are truly doing the lord's work.

I didn't check stuff in detail, but I trust that you have tested configs and such and are happy with your function interfaces.

Just a few minor requests for docstrings. 

The only unexpected thing I saw was the change in the beam filename templates, see the comment.

2024-10-08 09:25 UTC, iabrilcabezas commented on sofind/products/beams/beams_v4_20240115.yaml
`sofind/sofind/products/beams/beams_v4_20240115.yaml` -> `sofind/sofind/products/beams/beams_v4_day_20240115.yaml`

2024-10-08 09:41 UTC, iabrilcabezas commented on sofind/products/beams/beams_v4_20240115.yaml
I've also deleted `beam_v4_20230130_snfit.yaml` (unofficial beam product release from Sigurd)

2024-10-09 08:22 UTC, iabrilcabezas commented
I think this is all!

2024-10-09 17:58 UTC, zatkins2 commented on sofind/products/beams/beams_v4_20240115.yaml
thanks!

2024-10-09 18:04 UTC, zatkins2 approved these changes

2024-10-09 18:04 UTC, merged